### ISSUE TITLE
Verify: Vanithsizsia reports name as the Open Sea and can't be edited

### ISSUE THREAD

**Issue by kf106** [kf106/orthoverse-prismarine#31]
The owner of Vanithsizsia reports that their land name is not displayed correctly, and although the edit bar appears, they can't edit with right and left click. They can edit other tokens that are placed on the map.

**Comment by kf106** [comment]
Reproduced with other tokens, for example Camtubyala

**Comment by ricp** [comment]
Sounds weird indeed! I was looking at the code and we may have a case problem here, although it may not be related to this issue.

L62 in ethereum.js    `if (player.ethereum.wallet === landOwner)`

When voxel.json is generated the owner address is lowercased (in orthoverse-offline voxel-map-data.js L16), so it may cause problems and we should do:

`if (player.ethereum.wallet.toLowercase() === landOwner)`

**Comment by kf106** [comment]
Token now reported correctly. Needs rechecking after database shift

**Comment by kf106** [comment]
I'm still seeing a bug like this, but I think the dynamic world loading using the database may solve it.

**Comment by kf106** [comment]
Looks like #79 fixed this.
